import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Search, Sun } from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Fixed background with effects */}
        <div className="fixed inset-0 w-full h-screen bg-[#041016] -z-10">
          {/* Glowing blobs */}
          <div className="absolute top-[5%] left-[25%] w-[450px] h-[400px] rounded-full bg-[#216389] opacity-50 blur-[8rem]" />
          <div className="absolute top-[10%] left-[45%] w-[700px] h-[500px] rounded-full bg-[#216389] opacity-50 blur-[8rem]" />

          <div className="absolute bottom-[5%] left-[25%] w-[360px] h-[330px] rounded-full bg-pink-400 opacity-38 blur-[9rem]" />
          <div className="absolute bottom-[10%] left-[50%] w-[350px] h-[400px] rounded-full bg-pink-400 opacity-38 blur-[9rem]" />
        </div>

        {/* Header */}
        <div className="fixed top-0 left-0 w-full backdrop-blur-md border-b border-white/20 z-50">
          <div className="w-1/2 mx-auto px-4 py-4 flex items-center justify-between">
            <nav className="flex justify-between items-center w-full">
              <Link href={"/"}>
                <div className="text-xl font-bold">Abhinav Prajapati</div>
              </Link>
              <div className="flex items-center space-x-6">
                <a
                  href="#blog"
                  className="hover:text-yellow-400 transition-colors"
                >
                  Blog
                </a>
                <a
                  href="#projects"
                  className="hover:text-yellow-400 transition-colors"
                >
                  Projects
                </a>
                <a
                  href="#uses"
                  className="hover:text-yellow-400 transition-colors"
                >
                  Uses
                </a>
                <a
                  href="#about"
                  className="hover:text-yellow-400 transition-colors"
                >
                  About
                </a>
                <button
                  aria-label="Search"
                  className="hover:text-yellow-400 transition-colors"
                >
                  <Search size={20} />
                </button>
                <button
                  aria-label="Toggle theme"
                  className="hover:text-yellow-400 transition-colors"
                >
                  <Sun size={20} />
                </button>
              </div>
            </nav>
          </div>
        </div>

        {/* Main content */}
        <div className="pt-16">{children}</div>
      </body>
    </html>
  );
}
